### ISSUE TITLE
Erreur de la valeur "Online"

### ISSUE THREAD

**Issue by EricGE01** [NebzHB/plugin-AdGuard#3]
Si le serveur Adguard n'est plus joignable (Shutdown ou autre) avec la valeur de la commande "Online" reste à 1.
Dans le log Adguard on retrouve :
`[2021-09-11 07:50:11][ERROR] : Impossible de communiquer GET avec le serveur AdGuard 192.168.59.231 status ! Message : {}`

**Comment by NebzHB** [comment]
fixé dans https://github.com/NebzHB/plugin-AdGuard/commit/6ba5fd992f7979372c7c5039fd879764de3b501f

**Comment by EricGE01** [comment]
testé -> parfait.
